# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - line_length
  - todo
  - function_parameter_count
  - unused_closure_parameter # Added this for readability purposes of the code.
  - function_body_length
  - statement_position
  - nesting
  - large_tuple
  - private_over_fileprivate
  - type_body_length
  - force_try # I need Realm to crash so I don't forget to increase the schema number

opt_in_rules:
  - empty_count

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods
  - Generated
  - ${PROJECT_NAME}/Generated

type_name:
  max_length:
    warning: 99
    error: 100
  min_length:
    warning: 2
    error: 3

identifier_name:
  max_length:
    warning: 99
    error: 100
  min_length:
    warning: 1
    error: 2
  excluded: # excluded via string array
    - id # identifier
    - i # for loop iteration
    - e # for error e
    - x # x axis
    - y # y axis
